import { readFileSync } from "node:fs";

const dataset = JSON.parse(
  readFileSync(new URL("../../public/data/country-centroids.json", import.meta.url))
);

// ISO alpha-2 country code -> [lon, lat] centroid, for geolocating country-coded
// feeds (IODA / Cloudflare Radar outages) that report no coordinates. Loaded once
// from the bundled dataset.
export const COUNTRY_CENTROIDS = dataset.centroids;

// Normalized country name -> ISO alpha-2, for feeds that report a country NAME
// instead of a code (State Dept travel advisories, ReliefWeb).
const COUNTRY_NAMES = dataset.names || {};

// Must stay in sync with normalize() in scripts/build-country-centroids.mjs —
// the lookup keys were generated by that function, so any divergence here turns
// into a silent miss rather than an error.
export function normalizeCountryName(value) {
  if (!value) return "";
  return String(value)
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/&amp;/g, "and")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+travel advisory$/, "")
    .replace(/^the\s+/, "")
    .trim();
}

// ISO alpha-2 for a country name, or null when it is not a country we can place
// (composite entries like "Mainland China, Hong Kong & Macau" have no centroid).
export function countryCodeForName(name) {
  return COUNTRY_NAMES[normalizeCountryName(name)] || null;
}

// [lon, lat] for a country name, or null. Callers should skip the entity on null
// rather than guessing a location.
export function centroidForCountry(name) {
  const code = countryCodeForName(name);
  return code ? COUNTRY_CENTROIDS[code] || null : null;
}
